### ISSUE TITLE
Notify handler typo

### ISSUE THREAD

**Issue by HP41** [debops/ansible-samba#10]
Notify handler is called via the wrong name:

tasks/main.yml Line39: 
notify: [ 'Check config samba' ]

handlers/main.yml Line3:
- name: Check samba config

**Comment by drybjed** [comment]
Thank you for catching that! I'm currently busy with other roles, I plan to revisit `debops.samba` at some point to update it to current practices. If you want, you could fix some issues via PRs to this role.

**Comment by HP41** [comment]
Sounds good, I'll keep it open :)
